"""init

Revision ID: 8b2ef5d0f2f3
Revises: 555c194f47b7
Create Date: 2016-09-24 16:44:26.654000

"""

# revision identifiers, used by Alembic.
revision = '8b2ef5d0f2f3'
down_revision = '555c194f47b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
